apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw2-app
  template:
    metadata:
      labels:
        app: cw2-app
    spec:
      containers:
      - name: cw2-app
        image: user1378/cw2-devops:latest
        ports:
        - containerPort: 3000
